### ISSUE TITLE
Failed to commit

### ISSUE THREAD

**Issue by k0pernicus** [alexcrichton/git2-rs#102]
hi!
This issue concerns my understanding of "how to commit a modification with this library?".

An objective to my program is to get all diff for all followed objects, commit them with a simple commit like "back_up", and create a new branch starting from this commit.

For example, if I modify "README.md" and "CONTRIBUTING.md", I want to commit these files with a single commit.

But, I don't understand how to commit these 2 files in a simple way...
I use methods from Repository structure, but I really don't understand how to deal with the "commit" method. :-/
This method contains a Tree reference - does this reference must contains those modifications?
The "parents" field must contains previous commit in the current branch, right?

Is it possible to explain to me how to simply commit modifications in existing files please?

Thanks a lot!

**Comment by alexcrichton** [comment]
Thanks for the report! I typically have to kinda reverse engineer some of this stuff myself, but [some of the examples](https://github.com/alexcrichton/git2-rs/tree/master/examples) may help here as well in the future (nothing specifically for a commit here I believe).

Currently the [`commit` method](http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.commit) has two things which are hard to get:

1. The list of parent commits, but you can fetch these through [`find_commit`](http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.find_commit) plus [`head`](http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.head) followed by [`target`](http://alexcrichton.com/git2-rs/git2/struct.Reference.html#method.target).
2. The tree of the repository at the time of the commit.

The tree is definitely the harder part to get here, but the basic idea to get one of those will be:

* Starting with a repository, [grab its index](http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.index)
* Use one of the [add methods](http://alexcrichton.com/git2-rs/git2/struct.Index.html#method.add) on the index to add files, for example [`add_path`](http://alexcrichton.com/git2-rs/git2/struct.Index.html#method.add_path)
* Once you're done, use [`write_tree`](http://alexcrichton.com/git2-rs/git2/struct.Index.html#method.write_tree) to create a tree in the database
* Pass that `Oid` back to [`find_tree`](http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.find_tree) to load the in-memory representation.
* Pass this `Tree` to the original `commit` method

Does that make sense?

**Comment by k0pernicus** [comment]
Hi!
Thank you for this great answer :-)

Your explanation make sense to me!
I've already code a simple method to do the first part of the job, but I missed to add files... -_-
A single question before to try program your solution : do I have to add the modified file in the path again, even if he's already in the tree (for example, the README.md created by default by Github)?

Thank you again :-)

**Comment by k0pernicus** [comment]
Ok, it works!

This is my ugly code to test the solution:

```
let r_reference = r.head().unwrap();
let r_commit_oid = match r_reference.target() {
    Some(oid) => oid,
    None => panic!("No commit!"),
};
// Get parents commits
let r_parent_commits = r.find_commit(r_commit_oid).unwrap();

// Grab the index of the index repository
let mut r_index = r.index().unwrap();

match r_index.add_path(Path::new("README.md")) {
    Ok(_) => println!("README.md has been added!"),
    Err(error) => println!("{}", error),
};

let new_oid = match r_index.write_tree() {
    Ok(new_oid) => new_oid,
    Err(error) => panic!("Error {}", error),
};

let new_tree = match r.find_tree(new_oid) {
    Ok(tree) => tree,
    Err(error) => panic!("New tree canno't be instanciated! {}", error),
};

let commiter = &Signature::now("Test", "Test").unwrap();

let new_commit = r.commit(None, commiter, commiter, "Test_msg", &new_tree, &[&r_parent_commits]);
// // Create a new remote in the repository, named "back_up"
let new_commit_oid = match new_commit {
    Ok(oid) => oid,
    Err(error) => panic!("No new commit, due to error {}!", error),
};

let new_commit = r.find_commit(new_commit_oid).unwrap();

let mut branch_back_up = r.branch("back_up", &new_commit, true);
match branch_back_up.as_mut() {
    Ok(branch) => match branch.set_upstream(Some("back_up")) {
        Ok(_) => println!("Branch 'back_up' has been updated!"),
        Err(error) => println!("Error due to {}", error),
    },
    Err(error) => panic!("Canno't upstream the branch 'back_up', due to error {}", error),
}
let refname = match branch_back_up.as_mut() {
    Ok(branch) => branch.get(),
    Err(error) => panic!("ERROR: {}", error),
};
// Set head!
r.set_head(refname.name().unwrap());
```

I only tried with README.md, but I will update the code and make the change to all modified files with the latest tree ;-)

Thanks a lot!! :-)

**Comment by alexcrichton** [comment]
> do have I to add the modified file in the path again, even if he's already in the tree (for example, the README.md created by default by Github)?

I think that if you've got changes to the file it needs to be added, otherwise it'll already be part of the index.

> This is my ugly code to test the solution:

Looks good to me! Glad it worked out :)
