### ISSUE TITLE
Should `Oid` implement `AsRef<[u8]>`

### ISSUE THREAD

**Issue by Nemo157** [alexcrichton/git2-rs#108]
Not entirely certain this makes sense, but it would allow avoiding a call to `as_bytes` when passing an `Oid` into functions taking in `&[u8]` generically.

Looking through `std` there's precedence in that `str.as_bytes()` and `AsRef::<[u8]>::as_ref(str)` are equivalent.

**Comment by alexcrichton** [comment]
I'd be fine with adding an impl!

**Comment by Nemo157** [comment]
Cool, I'll probably get to it in the next day or so.
