### ISSUE TITLE
Iterating over a revwalk swallows the error

### ISSUE THREAD

**Issue by carlosmn** [alexcrichton/git2-rs#112]
When there's an error during a `git_revwalk_next()` call (e.g. some of the data is corrupt). The iterator will swallow the message and simply stop the iteration. This makes it look like we're at the end of the requested history and there's no error to let us know that something bad happened.

I don't know of a good way to fix this while using the iterator traits, unfortunately.

**Comment by alexcrichton** [comment]
Oh! I guess I assumed that the only error was "we're done".

I think I'll sneak in a breaking change as it looks like 0.4.0 (just released) doesn't have too many users.

**Comment by carlosmn** [comment]
We don't pre-load the commit list (well, we sometimes do, but during the first `_next()`) so we can expect to be doing I/O during the walk. Which means that basically any error ever can happen.

In the repo I was looking at in particular, corruption meant that we fail to find one of the objects.

**Comment by alexcrichton** [comment]
Ok, cool, I'll just switch this to an iterator over `io::Result<Oid>` so this can be handled.

Perhaps the [documentation of `git_revwalk_next`](https://libgit2.github.com/libgit2/#HEAD/group/revwalk/git_revwalk_next) could be updated to indicate that an I/O error could be returned?

**Comment by carlosmn** [comment]
It's not just `git_revwalk_next()` that behaves this way. 90% of what libgit2 does is I/O so anything that's not an accessor can potentially return an I/O (or similar) error. The ref/branch iterators can return this as well (and even if IIRC we don't right now, that's an implementation detail which would go away with lmdb, same goes for config).

This is why the docs keep mentioning "or an error code" for functions. As a rule of thumb, anything can go wrong.

**Comment by alexcrichton** [comment]
Ah, ok! I'll do an audit to ensure we're returning a `Result` everywhere

**Comment by JeanMertz** [comment]
Thank you for this issue. I know it's old, and I'm not adding anything relevant, but I had the exact opposite response of "why is this iterator returning a result, while the [libgit2 documentation](https://libgit2.org/libgit2/#HEAD/group/revwalk/git_revwalk_next)  doesn't mention anything about possible errors that can happen?" (as Alex points out).

Realising that all these calls do IO to fetch their data obviously makes a lot of sense, given the way Git stores its data in `.git`. Thanks for explaining 👍
