### ISSUE TITLE
Casting `Object` via `as_type()` and references

### ISSUE THREAD

**Issue by carlosmn** [alexcrichton/git2-rs#113]
It looks like `Object`'s `as_{tree,commit,blob,tag}()` is meant for situations where you keep hold of the `Object` variable and need the specific type for a function call or similar. I'm trying to build a function where I accept an extended-sha1 string and return a tree (wrapped in `Option` and/or `Result`). But the "obvious" way of writing this, something like

```rust
fn resolve_tree<'repo>(repo: &'repo Repository, expr: &str) -> Option<&'repo Tree<'repo>> {
    repo.revparse_single(expr).ok()
        .and_then(|o| o.peel(ObjectType::Tree).ok())
        .and_then(|t| t.as_tree())
}
```

doesn't work, since `t` doesn't live long enough (because `as_tree()` returns something tied to its life-time). I don't actually care about the generically-typed object and would rather get a `Tree<'repo>` out of it. I think that would involve consuming `self` which sounds fine for this.

Would something named more like `into_{tree,commit,blob,tag}()` be more appropriate for this kind of behaviour (does it exist but I'm missing it?). I know that looking up the object via `repo.find_tree()` ends up being pretty cheap since the object is cached by libgit2 but it'd feel cleaner not having to rely in that kind of information.

**Comment by alexcrichton** [comment]
Sounds plausible to me!

**Comment by alexcrichton** [comment]
Oh hm, in terms of destructors, does this work out ok? For example can you call `git_object_free` on a `git_blob`? Or vice-versa, can you call `git_blob_free` on a `git_object`? 

If not, that may just mean that a re-wrapping is needed in a newtype, but perhaps not the end of the wrold.

**Comment by carlosmn** [comment]
They're just wrappers around `git_object_free()` which then does the right thing. Nowadays they're actual functions but they used to just be macros which would do the casting for you. They serve no other purpose than having the types align in C.

**Comment by alexcrichton** [comment]
Excellent! I implemented this in https://github.com/alexcrichton/git2-rs/commit/e2869490401ab5335bae27e703b31c00f4120f7a and https://github.com/alexcrichton/git2-rs/commit/6573ca48d2811c3eda67b38c41e0e29a48393448
