### ISSUE TITLE
Testing problem.

### ISSUE THREAD

**Issue by ereichert** [alexcrichton/git2-rs#118]
I'm working on a release tool that relies on git2-rs.  Because there are no git2-rs traits to implement as mocks/stubs/doubles (whatever we're calling them these days) I'm having a really hard time figuring out a way to test my code that relies on git2-rs.  The failure cases are the really tough ones to test without traits to implement.  I can't even think of a way to create a bad git repo that would exhibit the kinds of errors I need to test.

For an example see: https://github.com/ereichert/cargo-release/blob/feature/branch_check/src/main.rs#L196

Would you consider a pull request that adds traits to the public API?

Keep in mind I'm still working my way through Rust's testing story so there may be a way to do this without traits I'm failing to grasp (other than doing actual side effecting git2-rs calls).  If you won't consider the addition of traits to git2-rs could you suggest a way to test my code?

**Comment by alexcrichton** [comment]
Hm yeah so it's true in general that mocking in Rust tends to be more difficult as it requires a trait abstraction boundary basically. I'd personally recommend for now that the trait would probably want to be local in your application, and then the application swaps it out. Traits for functionality don't necessarily belong in this library itself unless there's multiple implementations of something, but it may end up turning out differently!

**Comment by ereichert** [comment]
Not being able to easily swap out dependencies for testing is definitely a missing piece in the Rust testing story.  In my case I'm going to have to create a wrapper for my wrapper just for testing purposes.

I understand your position however.

Maybe Rust needs a tool that can create testing facades for any library like git2-rs that doesn't need traits itself but code that relies on it does.

Thanks for the time.
