### ISSUE TITLE
How to connect a remote that requires authentication?

### ISSUE THREAD

**Issue by sunnyone** [alexcrichton/git2-rs#121]
I want to connect a remote that requires authentication, but Remote#connect() doesn't have a parameter to pass credentials. How to do it with git2-rs?

I tried to connect with examples/fetch.rs, an error has occured at [line 79](https://github.com/alexcrichton/git2-rs/blob/master/examples/fetch.rs#L79):

> error: [23/-1] authentication required but no callback set

**Comment by alexcrichton** [comment]
This is done via the [`RemoteCallbacks::credentials` callback](http://alexcrichton.com/git2-rs/git2/struct.RemoteCallbacks.html#method.credentials). I think that if you can forgo the `connect` in favor of a direct [fetch](http://alexcrichton.com/git2-rs/git2/struct.Remote.html#method.fetch) where the callbacks can be specified.

Let me know though if you still run into trouble!

**Comment by sunnyone** [comment]
Thank you for your reply. It works with the fetch() method.
