### ISSUE TITLE
Support for colors, integrated with term library

### ISSUE THREAD

**Issue by joshtriplett** [alexcrichton/git2-rs#122]
I just filed https://github.com/libgit2/libgit2/issues/3710 requesting support for colors in libgit2's config API.  Once that goes in, I'd love to have support in git2-rs that integrates with the [term library](https://stebalien.github.io/doc/term/term/).  In particular, `git2::Config::get_color` could return a `git2::Color` object, which in addition to methods to return the data that libgit2 provides, could have a method that takes a `term::Terminal` and sets the color accordingly.

**Comment by alexcrichton** [comment]
Seems reasonable to me! (once this exists underneath)

**Comment by joshtriplett** [comment]
I just published the [colorparse](https://crates.io/crates/colorparse) crate, which parses a git-style color string and returns an `ansi_term::Style` object.  I think that solves most of this, without needing support in libgit2.

**Comment by alexcrichton** [comment]
Awesome! I think this is ok to close in that case? Or do you think it should be integrated directly into git2-rs?

**Comment by joshtriplett** [comment]
There's probably some useful common functionality that could be extracted to handle the flags like `color.ui` and `color.<cmd>`, but I don't think it'll be obvious what that should look like until it has a few users.  I'll close this for now; it can always be reopened.
