### ISSUE TITLE
Please support distant working with remote repositories

### ISSUE THREAD

**Issue by althonos** [alexcrichton/git2-rs#133]
Hi, 
right now working with remote repositories requires to clone the repository to a local path ; however it would be interesting to have access to references of the remote repository without having to clone it first (like the `git ls-remote` terminal command). It would allow to check for new commits in the remote repository and for instance only clone the latter if needed (without having to clone the remote repo all the time or having a local copy of the remote and running `fetch` all the time).

**Comment by alexcrichton** [comment]
Neat idea! You may want to report this feature request to upstream libgit2 as well?

**Comment by althonos** [comment]
Wouldn't it be possible to use [git_remote_ls](https://libgit2.github.com/libgit2/#HEAD/group/remote/git_remote_lsl) to get a remote_head reference, and then have access to the master branch oid ? It would be possible that way to know the status of the remote branch :)

**Comment by alexcrichton** [comment]
Perhaps! I don't know how to get your hands on a `git_remote`, however, without going through a `git_repository` originally

**Comment by alexcrichton** [comment]
I'm gonna close this for now as I think it's something libgit2 doesn't support, but feel free to file an upstream bug!

**Comment by althonos** [comment]
OK, no prob ! ;)
