### ISSUE TITLE
Please provide bindings for git_reference_create_matching and git_reference_symbolic_create_matching

### ISSUE THREAD

**Issue by joshtriplett** [alexcrichton/git2-rs#135]
git2-rs provides bindings for `git_reference_create` (`Repository::reference`) and `git_reference_symbolic_create` (`Repository::reference_symbolic`), but not the safer versions that take an expected current OID value.  Please consider adding bindings for those as well.  (In hindsight, the ideal API would have been a single function that accepted an Option<Oid>, but now that the unsafe versions exist, the safer versions should take an Oid.)

**Comment by alexcrichton** [comment]
Sounds like a good idea to me! Note that nothing was really intentionally left out, just happened to forget it at the time :)
