### ISSUE TITLE
Build instructions didn't work for me

### ISSUE THREAD

**Issue by xaocon** [alexcrichton/git2-rs#147]
The instructions for building on OSX didn't work for me. I'm on OSX 10.11.5 if that helps anyone reproduce:

```
% brew --version
Homebrew 0.9.9 (git revision d345; last commit 2016-05-22)
Homebrew/homebrew-core (git revision 994a3; last commit 2016-05-23)
```

The fix is simple enough, just using

``` sh
export OPENSSL_ROOT_DIR=`brew --prefix openssl`
```

worked well in place of the two exports in the current instructions. The upstream source of your instructions still has the other commands so maybe it's just my system.

**Comment by alexcrichton** [comment]
Hm, odd! Wanna send a PR?

**Comment by alexcrichton** [comment]
The retooled build in #353 should have fixed this.
