### ISSUE TITLE
Implement Eq for Commit

### ISSUE THREAD

**Issue by jrvidal** [alexcrichton/git2-rs#153]
Would it be reasonable to implement `Eq` for `Commit`, `Tree`, `Blob`, etc...?

**Comment by alexcrichton** [comment]
If there's an underlying method in libgit2, sure! If not, though, then it may be best to just equate the oid values

**Comment by jrvidal** [comment]
I did not check whether there is such a method, I just thought it might be convenient. If that is not the case and given the goal of being close to libgit2, please feel free to dismiss this request. Thanks!

**Comment by alexcrichton** [comment]
Ah ok I just checked and it looks like libgit2 doesn't have direct bindings for these functions, so I'm gonna close for now. Thanks for the report though!
