### ISSUE TITLE
failed connecting agent

### ISSUE THREAD

**Issue by DoumanAsh** [alexcrichton/git2-rs#154]
I got credentials from git2::Cred::ssh_key_from_agent(&name)

But then when i download:
i get error about failing to contact agent(ssh?)
`{ code: -1, klass: 23, message: "error authenticating: failed connecting agent" }`

But `git2::Cred::ssh_key_from_agent(&name)` returned ok

Code:
https://github.com/DoumanAsh/lazy-git-ext/blob/master/src/lib.rs#L225-L254

Sadly i cannot get stack traces :( For some reason all symbols are removed from my debug builds

**Conf:**
Windows 10 x64
rustc 1.10.0 (cfcb716cf 2016-07-03)
gnu toolchain

**Comment by alexcrichton** [comment]
Oh the `ssh_key_from_agent` doesn't actually connect to the SSH agent, but rather just creates an object which indicates that the auth code should eventually connect to the agent. If you run `strace`, what does the syscall log look like?

Also, what platform are you on? Symbols being removed sounds quite odd!

**Comment by DoumanAsh** [comment]
Oh,  i didn't thought... not really obvious.
I'll try strace.

And sadly i'm on windows with no proper backtrace for some reason

**Comment by DoumanAsh** [comment]
The problem with backtrace is due to #33985 :(

**Comment by alexcrichton** [comment]
Oh sorry strace (at least as far as I know) is just a Linux tool, so that's explain why it wouldn't work on Windows!

Could you try adding some debugging to see how your credential callback is being invoked and what it's returning?

**Comment by DoumanAsh** [comment]
It is always returns SSH Cred:
```
 [master ≡ +0 ~1 -0 !]> .\target\debug\git-sync.exe
Fetching origin
download
cred_callback(url=git@github.com:DoumanAsh/lazy-git-ext.git, username=Some("git"))
result ssh is ok? =true
thread '<main>' panicked at 'Cannot fetch: Error { code: -1, klass: 23, message: "error authenticating: failed connecting agent" }', ../src/libcore\result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
I vaguely remember libgit2 having a particular protocol to select something from the agent, it first requires a `git2::Cred::username` folllowed by `git2::Cred::ssh_key_from_agent` (with the same username). Maybe that's relevant?

**Comment by DoumanAsh** [comment]
Hm...  maybe the problem is that i'm getting name 'git' always.
Not sure if there is a proper way to retrieve username from repository itself :(

**Comment by alexcrichton** [comment]
Oh yeah one thing that Cargo does at least is that it tries multiple usernames to connect to the SSH agent. First it does what's in the URL, but "git" probably isn't in the agent, so then it falls back to the current username, etc.

Maybe that's what's up?

**Comment by DoumanAsh** [comment]
I tried to hard-code my username but now i'm getting:
`'Cannot fetch: Error { code: -1, klass: 23, message: "username does not match previous request" }`

P.s. is it ok that i get crash when my callback panics?

**Comment by alexcrichton** [comment]
Ah yeah I'm `acrichto` on IRC, feel free to ping me.

**Comment by DoumanAsh** [comment]
@alexcrichton I'm not sure if there is just mis-use of git2 API or maybe limitation of libgit...
I don't really know how to debug out this issue.
What should we do with this issue?

**Comment by alexcrichton** [comment]
@DoumanAsh oh on Windows I think `ssh-agent` is rarely running, and if it is it you likely need to jump through hoops to get libssh2 to connect to it unfortunately.

**Comment by DoumanAsh** [comment]
@alexcrichton In my case it is auto-started when i open my powershell console so that should not be the case

**Comment by alexcrichton** [comment]
Maybe libssh2 doesn't recognize how ssh-agent is started in powershell? I'm not entirely certain how it works, as on Unix they communicate over Unix sockets which I suspect aren't available on Windows...

**Comment by DoumanAsh** [comment]
Hm.... isn't it libgi2 who is responsible for communicatin with ssh-agent?
I thought all this stuff was implemented as part of it...

I'm not sure how it all works underlying but in any case git is fine with the way ssh-agent works on Windows, so i'm not sure what could be an issue.

**Comment by alexcrichton** [comment]
I believe libssh2 is the one that implements the protocol of actually connecting to the agent. The libgit2 library just tells libssh2 "please connect to the local agent"

**Comment by DoumanAsh** [comment]
@alexcrichton Sorry for not responding for quite some time. But it seems i found quite interesting thing: libssh2 supports only pageant on Windows, but i still haven't found relevant notes over libssh2 site.

So it might be possible that libgit2 is limited on Windows....

**Comment by alexcrichton** [comment]
Ah yeah I wouldn't be too surprised by that unfortunately :(

**Comment by DoumanAsh** [comment]
I suppose issue is closed then. Nothing to do about that.
