### ISSUE TITLE
Check for presence of a config value

### ISSUE THREAD

**Issue by olivernn** [alexcrichton/git2-rs#158]
I'm trying to check whether a particular value exists in git config, but I don't think its possible?

It seems that there is no specific method for checking if a key exists, and all the methods that pull out values return a `Result` not an `Option` which makes it difficult to differentiate between a key not being present or an issue when getting a value for a key.

Is this something that could be supported? Or Am I missing something obvious?

Thanks for the great library by the way!

**Comment by alexcrichton** [comment]
I think this may be communicated through the error type perhaps? If you inspect the error it probably has a particular code/class for "not present" vs "failed to parse"

(note that I'm just guessing though, I haven't scrutinized libgit2 for this myself)

**Comment by alexcrichton** [comment]
Closing as I think this'll probably be communicated via the error.
