### ISSUE TITLE
Index::len() reports how many files there are, not what is added to index

### ISSUE THREAD

**Issue by matthiasbeyer** [alexcrichton/git2-rs#159]
I'm not sure whether I understand all things correctly here, but from what I see, `Index::len()` reports the number of _files_ that are in the working directory. Semantically, I would expect the number of files that are added to the index.

Maybe I am misunderstanding something.

What I basically try to do is to commit if the index contains files, if not do nothing. But I have no way of finding out whether the `Index` is empty or not... or at least I do not see one.

**Comment by alexcrichton** [comment]
This currently corresponds to the [`git_index_entrycount`](https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_entrycount) function, so it may be not appropriately named perhaps?

As to what it's actually counting, that may be an issue for upstream libgit2 rather than here (as this is just delegating)

**Comment by matthiasbeyer** [comment]
Yes, not properly named.

Anyways, from what I understand, `git_index_entrycount` should return the number of entries added to the index, so the number of `git add`ed paths, am I correct?

Because it does not, from what I see.

**Comment by alexcrichton** [comment]
Hm perhaps that's a bug report for upstream libgit2 then?

**Comment by carlosmn** [comment]
This is how the git index works. The number of tracked files and the number of items in the index are the same number. The upstream bug was closed as a misunderstanding, so it looks like this bug can be closed the same way.

**Comment by alexcrichton** [comment]
Oh awesome, thanks @carlosmn!
