### ISSUE TITLE
status_should_ignore only works for absolute paths

### ISSUE THREAD

**Issue by jacwah** [alexcrichton/git2-rs#164]
Calling `Repository::status_should_ignore` on a path of the form `./filename` always returns true regardless of the current gitignore file. I tried canonicalizing the path instead which lead to the correct result being returned.

Is this a bug in git2-rs/libgit2? Am I missing something?

Cheers

**Comment by alexcrichton** [comment]
Ah unfortunately this may be behavior relative to libgit2, it looks like we just pass the file unmodified down to the lower layer.

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/libgit2/libgit2/issues/3979
