### ISSUE TITLE
git2::Delta should derive PartialEq and Eq

### ISSUE THREAD

**Issue by joshtriplett** [alexcrichton/git2-rs#167]
For convenient comparisons, `git2::Delta` should derive `PartialEq` and `Eq`.

**Comment by alexcrichton** [comment]
Hm right now this doesn't seem to exist in the main repo?

**Comment by joshtriplett** [comment]
@alexcrichton Not sure what you mean. The enum `Delta` (`Delta::Unmodified`, `Delta::Added`, ...) has existed for a while.

**Comment by alexcrichton** [comment]
Oh weird not sure how I missed that...
