### ISSUE TITLE
multivar support for Config

### ISSUE THREAD

**Issue by kejadlen** [alexcrichton/git2-rs#169]
Are there plans for adding multivar support for `Config`?

https://github.com/libgit2/libgit2/blob/master/src/config.c#L1032-L1043

Perhaps something like `set_multivar(name: &str, regexp: &str, value: &str)` or `set_multivar_string`?

**Comment by alexcrichton** [comment]
Sure! If an API is omitted from git2-rs it's almost guaranteed not to be intentional, just haven't gotten around to it yet :). Would you be interested in sending a PR for this?

**Comment by kejadlen** [comment]
Sure, I'd be happy to give it a shot! Does `set_multivar` work for the function name?

**Comment by alexcrichton** [comment]
Sure yeah, I typically just mirror libgit2

**Comment by kejadlen** [comment]
So it was pretty easy to implement, but I don't have the rust-fu to figure out how to test it.

```rust
    cfg.set_multivar("foo.bar", "^$", "baz").unwrap();
    cfg.set_multivar("foo.bar", "^$", "qux").unwrap();
```

The above works, but I can't get the borrow checker to play nice with making a collection of values from `ConfigEntries`. Any suggestions?

**Comment by alexcrichton** [comment]
Ah it's ok to omit tests, it's likely just a small shim around the libgit2 function anyway.

Want to send a PR so I can take a peek at the error and some code?

**Comment by kejadlen** [comment]
Done.

The error was when I was trying to test it - I couldn't figure out how to make a slice/vec of entries from `ConfigEntries` (to make sure that multiple values for a single name are present in the config) while appeasing the borrow checker.

**Comment by kejadlen** [comment]
Non-compiling test: https://github.com/kejadlen/git2-rs/blob/40d0978996dcf67b068a1e9a0953a099286b0395/src/config.rs#L559-L565

**Comment by alexcrichton** [comment]
Added in https://github.com/alexcrichton/git2-rs/pull/170
