### ISSUE TITLE
libgit2-sys: Fix compatibility with libressl

### ISSUE THREAD

**Issue by Keruspe** [alexcrichton/git2-rs#178]
Updating libgit2 to a tree where https://github.com/libgit2/libgit2/commit/567b83de5434abcc40eeeabb8167979240f27a8f is available should do the trick (backporting just this commit fixes the issue here).

Maybe issue a release afterwards?

**Comment by alexcrichton** [comment]
Sounds good to me! Want to send a PR?

**Comment by Keruspe** [comment]
Just noticed this issue was not closed once the PR got merged.
Actually, the latest release of libgit2-sys broke that. Indeed, libgit2 0.25.1 was released after that but for some reasons doesn't contain the relevant commits.

**Comment by alexcrichton** [comment]
Maybe it was after the 0.25.0 release? We could consider cherry-picking it back in if necessary
