### ISSUE TITLE
Using Git2 with Rayon.

### ISSUE THREAD

**Issue by Maaarcocr** [alexcrichton/git2-rs#187]
I have a long list of repository that I want to clone, thus I was thinking of parellalising this process using the map function exposed by Rayon onto the vector that contains the names of the repos. 
I have tried this, but it seems not to work. 
When I run `cargo run` the application starts, but after a while it terminates even before the end of my main (it doesn't print the last print statement I have at the end of the main, outside the map). Also most of repos are cloned, but the big ones are not.
When I run the same program using the normal map function it works fine (even though it is much slower)
Is it safe to use Git2 with Rayon?

**Comment by alexcrichton** [comment]
It should be! Mind sharing your program?

**Comment by Maaarcocr** [comment]
[This is my project](https://github.com/Maaarcocr/TWiS)
[This is where I clone one repo at time](https://github.com/Maaarcocr/TWiS/blob/master/src/get_info.rs)
[This is where I parallelize it](https://github.com/Maaarcocr/TWiS/blob/master/src/main.rs#L22)

Thanks for your support!

**Comment by alexcrichton** [comment]
@Maaarcocr hm I trimmed that down to not do github auth and manually clone a few repos, but it appears to work locally for me? Perhaps you could trim it down a bit to avoid the github bits?

**Comment by Maaarcocr** [comment]
I will try to use it with a hard coded vector.
I will let you know!

**Comment by Maaarcocr** [comment]
Okay now with a hardcoded Vec and a very slow connection I get this error: 
`*** stack smashing detected ***: target/debug/twis terminated`

Apart from this, could it be possible that rayon after a while a rayon "thread" (I don't know a better word to describe what rayon does) dies? A sort of timeout?

**Comment by alexcrichton** [comment]
Oh that sounds quite suspicious. My guess is some segfault in libgit2, either in libgit2 itself or how we're using it. I'd be surprised if rayon was at fault here. Do you have a reproduction I could try locally?

**Comment by alexcrichton** [comment]
I'm going to close this out of inactivity, but if a reproduction becomes available I can help take a look!
