### ISSUE TITLE
consider updating url dependency to 1.1

### ISSUE THREAD

**Issue by binarycrusader** [alexcrichton/git2-rs#192]
The latest nightly of cargo now wants url 1.1 while git2-rs still wants url 1.0.  To avoid possible conflicts, perhaps it's time to consider updating?

https://github.com/dhuseby/cargo-bootstrap/issues/19

**Comment by alexcrichton** [comment]
Thanks for the report! This crate already supports 1.1, however, as 1.0 (the listed requirement) is compatible with 1.1)

**Comment by alexcrichton** [comment]
(maybe this is a bug in cargo-bootstrap)?

Note that I'd also recommend cross-compiling Cargo. If you've got a cross compiler already it'll be much easier to bootstrap that way.

**Comment by binarycrusader** [comment]
Yes, it appears it is.  I'm sorry, my understanding of how semantic versioning worked in Cargo was wrong which lead me to believe that this dependency should be updated.  I now understand that 1.1 is allowed by the dependency specification.

**Comment by alexcrichton** [comment]
No worries! Not the first time I've seen this bug :)
