### ISSUE TITLE
Broken link to the documentation on crates.io

### ISSUE THREAD

**Issue by teiesti** [alexcrichton/git2-rs#195]
If you try to open this crates' documentation on [crates.io](https://crates.io/crates/git2), the link leads to https://docs.rs/git2-rs. On that page you find a "The requested crate does not exist" since the documentation is available at https://docs.rs/git2.

**Comment by alexcrichton** [comment]
Thanks for the report! This was fixed in https://github.com/alexcrichton/git2-rs/commit/f3db4416ac7a543ef2a9c2385664896085a7e3ef and it'll get updated with the next published version.
