### ISSUE TITLE
Document the reasons for not using a released version of libgit2

### ISSUE THREAD

**Issue by infinity0** [alexcrichton/git2-rs#198]
To make life easier for packagers, could you document **and update** the reasons why this package requires a particular commit of libgit2?

For the current version I am not seeing any reason this wouldn't work with v0.25.1 upstream, but the current submodule commit a59545de5e57769f858ed2657b9fb850675f227f differs from this by about 105 commits. The CHANGELOG diff is:

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 8544ac451..0ae75e156 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -3,12 +3,20 @@ v0.25 + 1
 
 ### Changes or improvements
 
+* `GIT_MERGE_OPTIONS_INIT` now includes a setting to perform rename detection.
+  This aligns this structure with the default by `git_merge` and
+  `git_merge_trees` when `NULL` was provided for the options.
+
 ### API additions
 
 ### API removals
 
 ### Breaking API changes
 
+* `clone_checkout_strategy` has been removed from
+  `git_submodule_update_option`. The checkout strategy used to clone will
+  be the same strategy specified in `checkout_opts`.
+
 v0.25
 -------
 [.. stuff below this hopefully isn't relevant since it's just retroactively updating descriptions of what is already in 0.25 ..]
```

`git_submodule_update_option` does not seem to be used by this rust crate, it's commented out in lib.rs.

**Comment by alexcrichton** [comment]
Historically libgit2 has never had a released version with all the various bug fixes that we needed .If it does now then I'd love to move to a released version! If a bug fix comes in though that we need I'd be likely to switch away from a released version to get the bugfix.

**Comment by alexcrichton** [comment]
I've just updated to 0.25.1, which should have fixes for all those, and the readme now has a note.

**Comment by infinity0** [comment]
Thanks!
