### ISSUE TITLE
On Windows, git SSH transport is broken

### ISSUE THREAD

**Issue by jethrogb** [alexcrichton/git2-rs#202]
When using libssh2 with the Windows CNG backend, if you call `libssh2_init(LIBSSH2_INIT_NO_CRYPTO)`, SSH is simply not functional, see https://github.com/libssh2/libssh2/issues/179. git2-rs used to not do this until https://github.com/alexcrichton/git2-rs/commit/071902aa24be86bbb5dc8512f2290f69968c2959 or https://github.com/alexcrichton/ssh2-rs/commit/891db584c1e7706e3075cea454f639ff3272c2a3. Now it does, and git+ssh has been broken on Windows versions of cargo ever since.

**Comment by alexcrichton** [comment]
Oh dear that'd do it, thanks for investigating! I'll look into a fix for this on our end.

**Comment by jethrogb** [comment]
Is it possible to add a test to cargo that tries to use SSH repos? This is apparently a not-often tested code path that breaks often.
