### ISSUE TITLE
How is zlib library being used?

### ISSUE THREAD

**Issue by TomasTomecek** [alexcrichton/git2-rs#206]
This is just a question: where can I see usage of zlib? I'm trying to slim down external dependencies in my crate and currently the only externally called C library is zlib, hence I'm interested to know if it's feasible to guard zlib via feature.

**Comment by alexcrichton** [comment]
AFAIK it's used by libgit2, which depends on libz

**Comment by TomasTomecek** [comment]
Thank you for such a quick answer: you're correct: https://github.com/libgit2/libgit2/blob/a6d833a29e100cae66d5144367e9102d093d4dbd/src/zstream.c#L8

Funny thing is that libgit2 is statically linked when compiling project using git2-rs. @alexcrichton do you think it's possible to statically link with libz?

**Comment by alexcrichton** [comment]
[Certainly](https://github.com/alexcrichton/libz-sys/blob/master/build.rs#L23-L27)!

**Comment by TomasTomecek** [comment]
Awesome! Thank you so much!
