### ISSUE TITLE
`libgit2-sys` Version `0.6.11` fails to build with LibreSSL

### ISSUE THREAD

**Issue by ibabushkin** [alexcrichton/git2-rs#212]
This seems to be caused by https://github.com/libgit2/libgit2/issues/4220 - upstream is preparing a new release: https://github.com/libgit2/libgit2/issues/4227. Version `0.6.10` is known to work. I'm not sure we can do anything about it *here*, but I think it should be at least pointed out.

**Comment by alexcrichton** [comment]
Thanks for the report! We can be sure to update as soon as this is fixed upstream
