### ISSUE TITLE
Fails to build due to missing URL in submodule it should not have even touched??????

### ISSUE THREAD

**Issue by raingloom** [alexcrichton/git2-rs#227]
Preface: my `$HOME` and `/` are both Git repositories, with a `.gitignore`, that first blacklists everything and then selectively re-adds paths.

[gist with build output](https://gist.github.com/raingloom/1b72608d8c4e13f0556a8a596519cf14)

The submodule part:
```
--- stderr
fatal: No url found for submodule path '../../../../../.emacs.d/local/i3-emacs' in .gitmodules
```

I don't know what's going on but it's touching my config files. That's major ugliness.

My wild guess is: some part of the code is scanning for a `.git` directory up in the file system or checking `$PWD` for it and it sees my `$HOME`'s `.git`.

**Comment by alexcrichton** [comment]
Thanks for the report, but that's actuall a red herring, this is the real error:

```
/home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.4.6/libgit2/src/openssl_stream.c:204:19: error: storage size of ‘git_stream_bio_method’ isn’t known
 static BIO_METHOD git_stream_bio_method = {
                   ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/git2.dir/build.make:1575: CMakeFiles/git2.dir/src/openssl_stream.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/git2.dir/all] Error 2
```

**Comment by muld0r** [comment]
@alexcrichton looks like there actually is a bug here if the user (for whatever reason) has their `$CARGO_HOME` in a git repository, and `libgit2-sys` is built in there (e.g. as a dependency of cargo).

Hit into this when building cargo under [buildroot](https://buildroot.org), but looks like there are other circumstances (such as above where the user has their whole home under source control).

The build script (erroneously?) calls `git submodule update --init`, which will update all modules in the superproject. I don't think this was intended though - we only wanted to populate the libgit2 directory / submodule, not all submodules / directories above us.

This can be corrected by calling `git submodule update --init .`, to specify we only want to populate the `libgit2` submodule.

Is this something I should create a new issue for? Happy to raise a PR / issue for it.
