### ISSUE TITLE
Build failure due to libssh2 issues on Mac

### ISSUE THREAD

**Issue by metacritical** [alexcrichton/git2-rs#228]
I was trying to build git2-rs on Mac. And it gave and unusual error 

`thread 'main' panicked at 'libgit2 failed to find libssh2, and SSH support is required',
`
I have installed libssh2 and openssl already. Has anyone else faced a similar issue compiling on a Mac?

Following is the complete BACKTRACE.

>> cargo build
   Compiling libc v0.2.26
   Compiling pkg-config v0.3.9
   Compiling bitflags v0.9.1
   Compiling matches v0.1.6
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.5
   Compiling percent-encoding v1.0.0
   Compiling gcc v0.3.51
   Compiling idna v0.1.4
   Compiling curl-sys v0.3.14
   Compiling libz-sys v1.0.16
   Compiling openssl-sys v0.9.14
   Compiling url v1.5.1
   Compiling cmake v0.1.24
   Compiling libssh2-sys v0.2.6
   Compiling libgit2-sys v0.6.12
error: failed to run custom build command for `libgit2-sys v0.6.12`
process didn't exit successfully: `/Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-c70b874f16488644/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/Users/pankajdoharey/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.12/libgit2" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_CLAR=OFF" "-DCMAKE_INSTALL_PREFIX=/Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Failed
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Success
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Looking for SSLCreateContext in /System/Library/Frameworks/Security.framework
-- Looking for SSLCreateContext in /System/Library/Frameworks/Security.framework - found
-- Checking for module 'libcurl'
--   Found libcurl, version 7.54.0
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser version 2 was not found; using bundled 3rd-party sources.
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8") 
-- Checking for module 'libssh2'
--   Package 'libssl', required by 'libssh2', not found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Found Iconv: -L/usr/lib -liconv
-- Performing Test IS_WALL_SUPPORTED
-- Performing Test IS_WALL_SUPPORTED - Success
-- Performing Test IS_WEXTRA_SUPPORTED
-- Performing Test IS_WEXTRA_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Success
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Performing Test IS_WNO-DEPRECATED-DECLARATIONS_SUPPORTED
-- Performing Test IS_WNO-DEPRECATED-DECLARATIONS_SUPPORTED - Success
-- Looking for regcomp_l
-- Looking for regcomp_l - found
-- Looking for futimens
-- Looking for futimens - not found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--" "-j4"
Scanning dependencies of target git2
[  2%] Building C object CMakeFiles/git2.dir/src/attr.c.o
[  2%] Building C object CMakeFiles/git2.dir/src/annotated_commit.c.o
[  2%] Building C object CMakeFiles/git2.dir/src/attr_file.c.o
[  2%] Building C object CMakeFiles/git2.dir/src/apply.c.o
[  3%] Building C object CMakeFiles/git2.dir/src/attrcache.c.o
[  4%] Building C object CMakeFiles/git2.dir/src/blame.c.o
[  4%] Building C object CMakeFiles/git2.dir/src/blame_git.c.o
[  5%] Building C object CMakeFiles/git2.dir/src/blob.c.o
[  6%] Building C object CMakeFiles/git2.dir/src/branch.c.o
[  7%] Building C object CMakeFiles/git2.dir/src/buf_text.c.o
[  8%] Building C object CMakeFiles/git2.dir/src/buffer.c.o
[  8%] Building C object CMakeFiles/git2.dir/src/cache.c.o
[  9%] Building C object CMakeFiles/git2.dir/src/checkout.c.o
[  9%] Building C object CMakeFiles/git2.dir/src/cherrypick.c.o
[ 10%] Building C object CMakeFiles/git2.dir/src/clone.c.o
[ 11%] Building C object CMakeFiles/git2.dir/src/commit.c.o
[ 12%] Building C object CMakeFiles/git2.dir/src/commit_list.c.o
[ 12%] Building C object CMakeFiles/git2.dir/src/config.c.o
[ 13%] Building C object CMakeFiles/git2.dir/src/config_file.c.o
[ 13%] Building C object CMakeFiles/git2.dir/src/crlf.c.o
[ 14%] Building C object CMakeFiles/git2.dir/src/curl_stream.c.o
[ 15%] Building C object CMakeFiles/git2.dir/src/date.c.o
[ 16%] Building C object CMakeFiles/git2.dir/src/delta.c.o
[ 16%] Building C object CMakeFiles/git2.dir/src/describe.c.o
[ 17%] Building C object CMakeFiles/git2.dir/src/diff.c.o
[ 18%] Building C object CMakeFiles/git2.dir/src/config_cache.c.o
[ 19%] Building C object CMakeFiles/git2.dir/src/diff_driver.c.o
[ 19%] Building C object CMakeFiles/git2.dir/src/diff_file.c.o
[ 20%] Building C object CMakeFiles/git2.dir/src/diff_generate.c.o
[ 21%] Building C object CMakeFiles/git2.dir/src/diff_parse.c.o
[ 21%] Building C object CMakeFiles/git2.dir/src/diff_print.c.o
[ 22%] Building C object CMakeFiles/git2.dir/src/diff_stats.c.o
[ 23%] Building C object CMakeFiles/git2.dir/src/diff_tform.c.o
[ 24%] Building C object CMakeFiles/git2.dir/src/diff_xdiff.c.o
[ 24%] Building C object CMakeFiles/git2.dir/src/errors.c.o
[ 25%] Building C object CMakeFiles/git2.dir/src/fetch.c.o
[ 26%] Building C object CMakeFiles/git2.dir/src/fetchhead.c.o
[ 26%] Building C object CMakeFiles/git2.dir/src/filebuf.c.o
[ 27%] Building C object CMakeFiles/git2.dir/src/fileops.c.o
[ 28%] Building C object CMakeFiles/git2.dir/src/filter.c.o
[ 29%] Building C object CMakeFiles/git2.dir/src/fnmatch.c.o
[ 29%] Building C object CMakeFiles/git2.dir/src/global.c.o
[ 30%] Building C object CMakeFiles/git2.dir/src/graph.c.o
[ 31%] Building C object CMakeFiles/git2.dir/src/hash.c.o
[ 31%] Building C object CMakeFiles/git2.dir/src/hashsig.c.o
[ 32%] Building C object CMakeFiles/git2.dir/src/ident.c.o
[ 33%] Building C object CMakeFiles/git2.dir/src/idxmap.c.o
[ 34%] Building C object CMakeFiles/git2.dir/src/ignore.c.o
[ 34%] Building C object CMakeFiles/git2.dir/src/index.c.o
[ 35%] Building C object CMakeFiles/git2.dir/src/indexer.c.o
[ 36%] Building C object CMakeFiles/git2.dir/src/iterator.c.o
[ 36%] Building C object CMakeFiles/git2.dir/src/merge.c.o
[ 37%] Building C object CMakeFiles/git2.dir/src/merge_driver.c.o
[ 38%] Building C object CMakeFiles/git2.dir/src/merge_file.c.o
[ 39%] Building C object CMakeFiles/git2.dir/src/message.c.o
[ 39%] Building C object CMakeFiles/git2.dir/src/mwindow.c.o
[ 40%] Building C object CMakeFiles/git2.dir/src/netops.c.o
[ 41%] Building C object CMakeFiles/git2.dir/src/notes.c.o
[ 41%] Building C object CMakeFiles/git2.dir/src/object.c.o
[ 42%] Building C object CMakeFiles/git2.dir/src/object_api.c.o
[ 43%] Building C object CMakeFiles/git2.dir/src/odb.c.o
[ 43%] Building C object CMakeFiles/git2.dir/src/odb_loose.c.o
[ 44%] Building C object CMakeFiles/git2.dir/src/odb_mempack.c.o
[ 45%] Building C object CMakeFiles/git2.dir/src/odb_pack.c.o
[ 46%] Building C object CMakeFiles/git2.dir/src/offmap.c.o
[ 46%] Building C object CMakeFiles/git2.dir/src/oid.c.o
[ 47%] Building C object CMakeFiles/git2.dir/src/oidarray.c.o
[ 48%] Building C object CMakeFiles/git2.dir/src/oidmap.c.o
[ 48%] Building C object CMakeFiles/git2.dir/src/openssl_stream.c.o
[ 49%] Building C object CMakeFiles/git2.dir/src/pack-objects.c.o
[ 50%] Building C object CMakeFiles/git2.dir/src/pack.c.o
[ 51%] Building C object CMakeFiles/git2.dir/src/patch.c.o
[ 51%] Building C object CMakeFiles/git2.dir/src/patch_generate.c.o
[ 52%] Building C object CMakeFiles/git2.dir/src/path.c.o
[ 53%] Building C object CMakeFiles/git2.dir/src/patch_parse.c.o
[ 53%] Building C object CMakeFiles/git2.dir/src/pathspec.c.o
[ 54%] Building C object CMakeFiles/git2.dir/src/pool.c.o
[ 55%] Building C object CMakeFiles/git2.dir/src/posix.c.o
[ 56%] Building C object CMakeFiles/git2.dir/src/pqueue.c.o
[ 56%] Building C object CMakeFiles/git2.dir/src/proxy.c.o
[ 57%] Building C object CMakeFiles/git2.dir/src/push.c.o
[ 58%] Building C object CMakeFiles/git2.dir/src/rebase.c.o
[ 58%] Building C object CMakeFiles/git2.dir/src/refdb.c.o
[ 59%] Building C object CMakeFiles/git2.dir/src/refdb_fs.c.o
[ 60%] Building C object CMakeFiles/git2.dir/src/reflog.c.o
[ 60%] Building C object CMakeFiles/git2.dir/src/refs.c.o
[ 61%] Building C object CMakeFiles/git2.dir/src/refspec.c.o
[ 62%] Building C object CMakeFiles/git2.dir/src/remote.c.o
[ 63%] Building C object CMakeFiles/git2.dir/src/repository.c.o
[ 63%] Building C object CMakeFiles/git2.dir/src/reset.c.o
[ 64%] Building C object CMakeFiles/git2.dir/src/revert.c.o
[ 65%] Building C object CMakeFiles/git2.dir/src/revparse.c.o
[ 65%] Building C object CMakeFiles/git2.dir/src/revwalk.c.o
[ 66%] Building C object CMakeFiles/git2.dir/src/settings.c.o
[ 67%] Building C object CMakeFiles/git2.dir/src/sha1_lookup.c.o
[ 68%] Building C object CMakeFiles/git2.dir/src/signature.c.o
[ 69%] Building C object CMakeFiles/git2.dir/src/sortedcache.c.o
[ 69%] Building C object CMakeFiles/git2.dir/src/socket_stream.c.o
[ 70%] Building C object CMakeFiles/git2.dir/src/stash.c.o
[ 71%] Building C object CMakeFiles/git2.dir/src/strmap.c.o
[ 72%] Building C object CMakeFiles/git2.dir/src/status.c.o
[ 72%] Building C object CMakeFiles/git2.dir/src/stransport_stream.c.o
[ 73%] Building C object CMakeFiles/git2.dir/src/submodule.c.o
[ 73%] Building C object CMakeFiles/git2.dir/src/sysdir.c.o
[ 74%] Building C object CMakeFiles/git2.dir/src/tag.c.o
[ 75%] Building C object CMakeFiles/git2.dir/src/thread-utils.c.o
[ 75%] Building C object CMakeFiles/git2.dir/src/tls_stream.c.o
[ 76%] Building C object CMakeFiles/git2.dir/src/trace.c.o
[ 77%] Building C object CMakeFiles/git2.dir/src/transaction.c.o
[ 78%] Building C object CMakeFiles/git2.dir/src/transport.c.o
[ 78%] Building C object CMakeFiles/git2.dir/src/tree-cache.c.o
[ 79%] Building C object CMakeFiles/git2.dir/src/tree.c.o
[ 80%] Building C object CMakeFiles/git2.dir/src/tsort.c.o
[ 80%] Building C object CMakeFiles/git2.dir/src/util.c.o
[ 81%] Building C object CMakeFiles/git2.dir/src/varint.c.o
[ 82%] Building C object CMakeFiles/git2.dir/src/vector.c.o
[ 82%] Building C object CMakeFiles/git2.dir/src/worktree.c.o
[ 83%] Building C object CMakeFiles/git2.dir/src/zstream.c.o
[ 84%] Building C object CMakeFiles/git2.dir/src/transports/auth.c.o
[ 85%] Building C object CMakeFiles/git2.dir/src/transports/auth_negotiate.c.o
[ 85%] Building C object CMakeFiles/git2.dir/src/transports/cred.c.o
[ 86%] Building C object CMakeFiles/git2.dir/src/transports/cred_helpers.c.o
[ 87%] Building C object CMakeFiles/git2.dir/src/transports/git.c.o
[ 87%] Building C object CMakeFiles/git2.dir/src/transports/http.c.o
[ 88%] Building C object CMakeFiles/git2.dir/src/transports/local.c.o
[ 89%] Building C object CMakeFiles/git2.dir/src/transports/smart.c.o
[ 90%] Building C object CMakeFiles/git2.dir/src/transports/smart_pkt.c.o
[ 90%] Building C object CMakeFiles/git2.dir/src/transports/smart_protocol.c.o
[ 90%] Building C object CMakeFiles/git2.dir/src/xdiff/xdiffi.c.o
[ 91%] Building C object CMakeFiles/git2.dir/src/transports/winhttp.c.o
[ 92%] Building C object CMakeFiles/git2.dir/src/transports/ssh.c.o
[ 93%] Building C object CMakeFiles/git2.dir/src/xdiff/xemit.c.o
[ 94%] Building C object CMakeFiles/git2.dir/src/xdiff/xhistogram.c.o
[ 95%] Building C object CMakeFiles/git2.dir/src/xdiff/xmerge.c.o
[ 95%] Building C object CMakeFiles/git2.dir/src/xdiff/xpatience.c.o
[ 96%] Building C object CMakeFiles/git2.dir/src/xdiff/xprepare.c.o
[ 97%] Building C object CMakeFiles/git2.dir/src/xdiff/xutils.c.o
[ 97%] Building C object CMakeFiles/git2.dir/src/unix/map.c.o
[ 98%] Building C object CMakeFiles/git2.dir/src/unix/realpath.c.o
[ 99%] Building C object CMakeFiles/git2.dir/deps/http-parser/http_parser.c.o
[100%] Linking C static library libgit2.a
[100%] Built target git2
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/lib/libgit2.a
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/lib/pkgconfig/libgit2.pc
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/signature.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/oid.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/index.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/ignore.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/inttypes.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/attr.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/blame.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/oidarray.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/pack.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/revert.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/version.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/odb.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/status.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/net.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/tag.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/annotated_commit.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/config.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/branch.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/types.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/repository.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/clone.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/global.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/blob.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/cherrypick.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/submodule.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/errors.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/message.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/merge.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/pathspec.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/tree.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/odb_backend.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/graph.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/describe.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/rebase.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/worktree.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/stash.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/remote.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/strarray.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/reflog.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/cred_helpers.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/buffer.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/diff.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/time.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/index.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/config.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/repository.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/openssl.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/merge.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/stream.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/odb_backend.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/remote.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/reflog.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/diff.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/transport.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/hashsig.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/refs.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/filter.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/mempack.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/commit.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/sys/refdb_backend.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/trace.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/common.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/proxy.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/indexer.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/refspec.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/notes.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/transport.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/revwalk.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/patch.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/object.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/checkout.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/revparse.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/refs.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/reset.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/filter.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/transaction.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/stdint.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/commit.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2/refdb.h
-- Installing: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/include/git2.h
cargo:root=/Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out

--- stderr
-- Found Security /System/Library/Frameworks/Security.framework
-- Found CoreFoundation /System/Library/Frameworks/CoreFoundation.framework
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_CXX_FLAGS

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgit2.a(auth_negotiate.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgit2.a(winhttp.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgit2.a(auth_negotiate.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgit2.a(winhttp.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/lib/libgit2.a(auth_negotiate.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/pankajdoharey/Development/Rust/scmbag/target/debug/build/libgit2-sys-cb8569bca685a9b2/out/lib/libgit2.a(winhttp.c.o) has no symbols
thread 'main' panicked at 'libgit2 failed to find libssh2, and SSH support is required', /Users/pankajdoharey/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.12/build.rs:137
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like it's the most relevant:

```
-- Checking for module 'libssh2'
-- Package 'libssl', required by 'libssh2', not found
```

Do you have libssh2 installed through Homebrew? Or was it compiled from source as part of the libssh2-sys crate?

**Comment by metacritical** [comment]
I installed it through home-brew, but good idea will try compiling it with libssh2-sys crate aswell.

**Comment by alexcrichton** [comment]
Ah yeah, if it's removed in homebrew does the compilation succeed?

**Comment by metacritical** [comment]
libssh2 in installed through homebrew but it seems the issue is about building libgit2 so i am trying to manually build libgit2 and then again try. I hope it works.

**Comment by metacritical** [comment]
Installed libgit2 manually, still it doesnt work. I give up switching of FFI.
