### ISSUE TITLE
update libgit2 to 0.26

### ISSUE THREAD

**Issue by infinity0** [alexcrichton/git2-rs#230]
It builds fine against libgit2-sys 0.6.12 with no changes required, I was just able to produce a cargo 0.20 Debian package from it with automatically-generated `Depends: libgit2-26 (>= 0.26.0)`.

**Comment by alexcrichton** [comment]
This has actually [already been done](https://github.com/alexcrichton/git2-rs/pull/223), just hasn't been published yet, I'll do so.
