### ISSUE TITLE
Use native tls instead of curl/openssl

### ISSUE THREAD

**Issue by dns2utf8** [alexcrichton/git2-rs#231]
Hi all

I am currently forced to work on a mac and can not use my favorite cargo extensions like `cargo-update` or `cargo-tree` because they depend on curl/openssl.
This evening I tried to patch git2-rs but I failed.

Did you ever consider using [native-tls?](https://github.com/sfackler/rust-native-tls)

**Comment by alexcrichton** [comment]
Thanks for the report! The dependency comes from libgit2, though, not from the Rust code, which is much harder to change.
