### ISSUE TITLE
Build broken by git2 0.6.7

### ISSUE THREAD

**Issue by neithernut** [alexcrichton/git2-rs#245]
Since the release of `git2-0.6.7`, the CI builds ([example](https://travis-ci.org/neithernut/git-dit/builds/269655304?utm_source=github_status&utm_medium=notification)) of the `git-dit` project keep failing.

Given an iterator over `References`, it was previously possible to simply use a flat map (e.g. `referenceses.flat_map(git2::References::names)`) for expanding the `References` to names. This is no longer possible. I suspect the changes introduced by 7d4f3a4913f41ff075a6327c13f4ce6810c3384d cause compilation failure (due to the mutable reference _and_ the additional lifetime). It should be possible to work around this problem using a clause which collects the names.

I guess this is a wont-fix. The work-around is obvious, memory-safety is more important in this case and `git2` is pre-1.0. Hence, such interface changes are justified. The minor version should have probably been bumped rather than the patch-level, though.

**Comment by alexcrichton** [comment]
Thanks for the report and sorry for the breakage! My thinking was that yes, while this is breakage, it's fixing a memory soundness issue which wasn't possible to get right before, so you, as an app author, would want to know about it! If it's difficult to upgrade though I could consider yanking 0.6.7 and releasing 0.7.0

**Comment by alexcrichton** [comment]
Closing this now as I haven't heard much else along these lines.
