### ISSUE TITLE
Unable to build when installing cargo-update on macOS 10.13

### ISSUE THREAD

**Issue by lewisinc** [alexcrichton/git2-rs#257]
Having issues building git2-rs when installing cargo-update. I've tried setting `CMAKE_PREFIX_PATH` so cmake can find openssl's headers. Here's a log to see where exactly this fails building.

[log.txt](https://github.com/alexcrichton/git2-rs/files/1347248/log.txt)

[related issue filed at cargo-update](https://github.com/nabijaczleweli/cargo-update/issues/52#issuecomment-333382694)

I do have `openssl` and `libssh2` installed with Homebrew on my machine, so unless there's a variable I need to explicitly set now - I'm at a loss.

Thanks.

**Comment by djc** [comment]
I was debugging this issue with @alexcrichton. For now, you could work around this with `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` when running a cargo command.
