### ISSUE TITLE
Some structs are not documented

### ISSUE THREAD

**Issue by nbigaouette-eai** [alexcrichton/git2-rs#260]
I found two structs that are unfortunately not documented on docs.rs.

Can't remember the first one, but the second one is `SubmoduleUpdateOptions`:
* See `Submodule.update()` docs: https://docs.rs/git2/0.6.8/git2/struct.Submodule.html#method.update The `SubmoduleUpdateOptions` is not clickable.
* Searching for it returns no hit: https://docs.rs/git2/0.6.8/git2/index.html?search=SubmoduleUpdateOptions
* Source contains documentation: https://github.com/alexcrichton/git2-rs/blob/master/src/submodule.rs#L205-L210

What kind of glitch (if it's really one) could be causing this? Maybe a cargo issue?

**Comment by nbigaouette-eai** [comment]
Weirdly enough, this module is private? I cannot use it... Maybe that's why that it wasn't documented?

```
error[E0603]: module `submodule` is private
   --> src/git.rs:182:53
    |
182 |                         let mut submodule_options = git2::submodule::SubmoduleUpdateOptions::new();
    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

In any case because I cannot create a `git2::submodule::SubmoduleUpdateOptions`, I cannot call `git2::submodule::Submodule::update()`! :(

**Comment by alexcrichton** [comment]
Oh oops! These should be reexported at the root for sure and that I think would force them to be documented, thanks for finding this!

Would you be interested in sending a PR for this?

**Comment by nbigaouette-eai** [comment]
Sure, if it's as simple as the re-export, I'll give it a try!
