### ISSUE TITLE
Status unusable without libgit2-sys

### ISSUE THREAD

**Issue by glfmn** [alexcrichton/git2-rs#279]
In order to properly use the `Status` struct, I have to know which bit corresponds to which flag, which requires `libgit2-sys` as far as I can tell, unless I do lots of very manual testing to figure out which is which.

For more context, I'm writing a binary which pretty-prints git stats, and I'm using git2 to interact with the repository to gather the information I need.

**Comment by alexcrichton** [comment]
Sounds bad! Seems fine though to add various accessors as necessary to avoid needing libgit2-sys

**Comment by glfmn** [comment]
From the usage examples in the bit-flags crate, it seems that it should be possible to use the flags as follows:

```rust
bitflags! {
    struct Flags: u32 {
        const FLAG_A       = 0b00000001;
        const FLAG_B       = 0b00000010;
        const FLAG_C       = 0b00000100;
        const FLAG_ABC     = Self::FLAG_A.bits
                           | Self::FLAG_B.bits
                           | Self::FLAG_C.bits;
    }
}

fn main() {
    let e1 = Flags::FLAG_A | Flags::FLAG_C;
    let e2 = Flags::FLAG_B | Flags::FLAG_C;
    assert_eq!((e1 | e2), Flags::FLAG_ABC);   // union
    assert_eq!((e1 & e2), Flags::FLAG_C);     // intersection
    assert_eq!((e1 - e2), Flags::FLAG_A);     // set difference
    assert_eq!(!e2, Flags::FLAG_A);           // set complement
}
```

I think the problem may stem from a simple lack of `pub` on the declarations, though I need to double check.  Accessors that check for each bit and return a `bool` directly could definitely still be useful, less boilerplate that way.  Would you mind if I submitted a PR for this?

**Comment by alexcrichton** [comment]
Nah yeah definitely feel free to send a PR!

**Comment by glfmn** [comment]
**It turns out it's just an error on my part, I was looking at the wrong version of the `bitflags` crate.**

The associated constants shown above appeared in version 1.0 of `bitflags`.  It's a breaking change in `bitflags` and would likely be a breaking change in `git2-rs` as well.  If you would like I can still bump the `bitflags` version to 1.0 and make all the fix all the broken tests and such in `git2-rs`, but it would need to be in the next release.

I can also still add the helper methods.

**The fix** on my part was simply to use the unqualified `STATUS_WT_NEW` family of constants from git2.

**Comment by alexcrichton** [comment]
Ah ok, great! I know we'd for sure still welcome the helper methods!

**Comment by glfmn** [comment]
@alexcrichton Finally got to this, opening a PR shortly
