### ISSUE TITLE
`git2::Status::INDEX_NEW` vs `git2::STATUS_INDEX_NEW`

### ISSUE THREAD

**Issue by someguynamedmatt** [alexcrichton/git2-rs#291]
I noticed that in at least [one of the examples](https://github.com/alexcrichton/git2-rs/blob/master/examples/status.rs) `git2::STATUS_INDEX_NEW` was replaced in favor of `git2::Status::INDEX_NEW` via Pull #289. Playing around with with this lib I can't get my code to compile with the `git2::Status::INDEX_NEW`, but can with the former. Why is this? I've declared `git2 = "0.6"` in my `Cargo.toml` file, does it need to be more recent?

Thanks.

**Comment by alexcrichton** [comment]
Ah I believe that these changes just haven't been published to crates.io yet!

**Comment by someguynamedmatt** [comment]
Ah, gotcha. Thanks!
