### ISSUE TITLE
Wrong (elided) lifetimes for peel_to_*?

### ISSUE THREAD

**Issue by flodiebold** [alexcrichton/git2-rs#299]
The following code doesn't compile:
```rust
    let env_tree = tree.get_name("foo")
        .unwrap()
        .to_object(repo)?
        .peel_to_tree()?;
```
because the resulting `Tree` has the lifetime of the short-lived object reference, instead of the repository. Am I missing something, or is that wrong?

Currently, the signature for `peel_to_tree` is
```rust
fn peel_to_tree(&self) -> Result<Tree, Error>
```
, but shouldn't it be
```rust
fn peel_to_tree(&self) -> Result<Tree<'repo>, Error>
```
?

**Comment by alexcrichton** [comment]
Ah yeah I believe so!

**Comment by flodiebold** [comment]
Ok, I can make a pull request this evening.
