### ISSUE TITLE
Does this library guarantee thread safety?

### ISSUE THREAD

**Issue by kt10** [alexcrichton/git2-rs#306]
In origin C libgit2, because of its internal call to the LibSSH2 and OpenSSL, can NOT do `git push` 
in a multithreaded environment concurrently  !!

Is your crate fix this ?????

**Comment by alexcrichton** [comment]
It is indeed intended to provide thread safety! The underlying libs should all be configured to appropriately synchronize and all that, but if issues arise please let me know!
