### ISSUE TITLE
Cloning repo fails with 'invalid Content-Type: text/plain; charset=UTF-8; class=Net (12)'

### ISSUE THREAD

**Issue by jhaye** [alexcrichton/git2-rs#314]
Using the simple example on how to clone repos with this library, I tried cloning https://git.matrix.org/git/olm/

With git via CLI it works like expected, however when trying to do it with the example code it fails with `invalid Content-Type: text/plain; charset=UTF-8; class=Net (12)`.

**Comment by alexcrichton** [comment]
Hm I'm not quite sure what could be causing this, but this may be an issue for libgit2?

**Comment by jhaye** [comment]
It seems to be, I traced the error code back to libgit2's error handling when parsing.

This seems to be causing the error: https://github.com/libgit2/libgit2/blob/master/src/transports/http.c#L451

I guess I'll be handing down the issue to libgit2.

**Comment by jhaye** [comment]
So to summarise, this is an issue regarding protocol support: libgit2 does not support git's 'Dumb HTTP' protocol and as it is quite old there is no plan to support it in the future either. Closing as this is an issue unrelated to git2-rs.
