### ISSUE TITLE
Update libgit2 version

### ISSUE THREAD

**Issue by vors** [alexcrichton/git2-rs#316]
It looks like libgit2 submodule points to the version `v0.16.0`
```
 c9d59c6140fc365eb7ab950fb1a33187a949d403 libgit2 (v0.16.0-8925-gc9d59c614)
```

Which [dates back to 2012](https://github.com/libgit2/libgit2/tags?after=v0.21.1)

It's probably worth to update the libgit2 version.
I roughly checked the api differences and there are a lot.
Here is a small snippet.
On the left are the functions exposed by `libgit2-sys` crate, on the right current master of libgit2. There are many more screen like that.

![image](https://user-images.githubusercontent.com/816680/40596108-8e5ea494-61ed-11e8-95cd-18a6468d52ca.png)

**Comment by alexcrichton** [comment]
I think [that commit](https://github.com/libgit2/libgit2/commit/c9d59c6140fc365eb7ab950fb1a33187a949d403) is from 2018-02-27?

In any case an update is always welcome, should just be a PR!

**Comment by vors** [comment]
Ouh, sorry - got confused by the `git submodule` output!

**Comment by vors** [comment]
@alexcrichton I want to send a PR for libgit2 version bump, once there is a release with https://github.com/libgit2/libgit2/issues/4658 . Can you, please, outline the process? Can I assume that if it compiles and passes existing tests, then my update for the bindings is ok?

**Comment by vors** [comment]
Right, I'm unclear about what's the process to update the bindings to take the advantage of new APIs. I.e. is there some way to generate them / is there a way to test that they have proper signature, etc.

**Comment by alexcrichton** [comment]
Oh sure yeah, for this repository if you run `cargo run` in the systest directory it will.verify bindings are correct

**Comment by vors** [comment]
Oh wow, great test system!
