### ISSUE TITLE
Can the libgit2 dependency be reverted to a released version before 1.0?

### ISSUE THREAD

**Issue by aidancully** [alexcrichton/git2-rs#32]
Specifically, I'm asking for https://github.com/alexcrichton/git2-rs/commit/a20191dde5d482debb90b5913f03a58ca73720e2 to be backed out, and the bug to be resolved in some other way. The latest released libgit2 is v0.21.3, which doesn't include the new APIs that are now being relied upon... It doesn't seem right for a 1.0 release to depend on an unreleased library version.

**Comment by lucab** [comment]
libgit2 just saw a new 0.23.0 release with a newer API/ABI. @alexcrichton, can you please repoint the `git2-rs/libgit2-sys/libgit2` submodule to the `v0.23.0` upstream tag and add a safety check around pkg-config call to check for "0.23." in the string version?

I think this could be a good initial step to synchronize on 0.23 ABI and later come up with a proper solution to track soname bumps.

**Comment by alexcrichton** [comment]
Excellent! I'll try to sync to 0.23.0 soon, thanks for the heads up @lucab!

**Comment by alexcrichton** [comment]
Ok, this now depends on 0.23.0 and I think we'll try to track releases from now on.
