### ISSUE TITLE
is_path_ignored not working on windows

### ISSUE THREAD

**Issue by Eh2406** [alexcrichton/git2-rs#334]
steps to repro:
start a new cargo project `C:\> cargo new git2-test` then
check that `.gitignore` includes `/target`
add `git2 = "*"` to `Cargo.toml` and the following to `main.rs`

```rust
extern crate git2;

fn main() {
    let p_exe = std::env::current_exe().unwrap();
    println!("./target/debug == {:?}", p_exe.display());
    let repo = git2::Repository::discover(&p_exe).unwrap();
    println!("./.git == {:?}", repo.path().display());
    let ignored = repo.is_path_ignored(&p_exe).unwrap();
    println!("true == {:?}", ignored);
}
```

(or unzip the file [git2-test.zip](https://github.com/alexcrichton/git2-rs/files/2211357/git2-test.zip)) and do `cargo run`.

output is:
```cmd
C:\git2-test>cargo run
   Compiling git2-test v0.1.0 (file:///C:/git2-test)
    Finished dev [unoptimized + debuginfo] target(s) in 1.78s
     Running `target\debug\git2-test.exe`
./target/debug == "C:\\git2-test\\target\\debug\\git2-test.exe"
./.git == "C:/git2-test/.git/"
true == false

```
I expected the last line to be `true == true`

tested on windows 10 locally, reduced from appveyor testing https://github.com/rust-lang/cargo/pull/5733

**Comment by alexcrichton** [comment]
This is likely either a bug in libgit2 or a facet that we need to work around unfortunately :(

**Comment by alexcrichton** [comment]
Thanks for diagnosing this though!

**Comment by Eh2406** [comment]
I refined it as far as I can. I don't have the C knowledge to reported up stream.

If you have a suggestion for a workaround, I'm all ears.

**Comment by Eh2406** [comment]
That seems to work locally. Odd that `discover` did not need that conversion. What is the most reliable way to convert? `to_string_lossy`?

**Comment by Eh2406** [comment]
Also should we Implement that work around here or in each user of this crates?

**Comment by alexcrichton** [comment]
Yeah something like `to_string_lossy` would be reasonable, and I'd be fine with a fix in this crate itself

**Comment by dwijnand** [comment]
The other workaround, probably not worth considering but maybe worth studying, is https://github.com/BurntSushi/ripgrep/tree/master/ignore.
