### ISSUE TITLE
Submodule::url panics

### ISSUE THREAD

**Issue by mitsuhiko** [alexcrichton/git2-rs#348]
I have not found out why yet but we do a call to `Submodule::url` which is supposed to return an option but it panics unwrapping an internal option instead.

Apparently the return value of `git_submodule_url` is null which gets converted into `None` by `opt_bytes` and then unwrapped.

A stacktrace showing the issue can be seen here: https://github.com/getsentry/sentry-cli/issues/361

**Comment by alexcrichton** [comment]
Oh dear, seems bad!  Should be fixed now though!

**Comment by alexcrichton** [comment]
(fixed in https://github.com/alexcrichton/git2-rs/commit/350da2009cf3f2a1b0ae78875cfe1f2e0ce403e1)
