### ISSUE TITLE
[Question] Is the Transport API good for remote helpers?

### ISSUE THREAD

**Issue by drozdziak1** [alexcrichton/git2-rs#364]
# What am I trying to achieve?
I'm writing a remote helper for storing Git's objects on IPFS (yup, another one coming, hopefully it won't suck like all others). 

# What's stopping me?
I saw that `libgit2` makes available the elusive transport and subtransport APIs. Problem is I don't understand how they work and how a new [sub]transport can be registered and used for handling requests. 

But I'm not even sure that it's the thing I need. I plan to use the smart transport API (`fetch` and `push` capabilities in `man git-remote-helpers`) and would like to reuse IPFS-uploaded objects via their IPFS hashes. The problem with that is that I need to find a decent way to serialize all git's object tree node types and then reconstruct them within `git2`, and ugly hacks will likely ensue.

I'd appreciate your thoughts about `git2` and remote helpers. If you envision a good way to modify `git2` to comply with use cases like mine I'd be happy to contribute.

**I'm asking this here because I didn't get an answer on git's mailing list and the libgit2 IRC channel is dead**

**Comment by alexcrichton** [comment]
Thanks for the report! I think this sort of depends on your use case but libgit2's transport api works well enough for us to hook push/pull/fetch to inject the `curl` crate, for example. (to do HTTP requests). That's distinct from ODB stuff (which isn't bound yet in Rust), but may work for your use case?

**Comment by drozdziak1** [comment]
Unfortunately I'm rolling my own data format for the IPFS backend, I elected that automated HTTP is not enough for my use case, because I need a custom data format so that git's DAG is reflected on IPFS. @alexcrichton Do you have an arch in mind for ODB already? What should I look at to understand how to hook bindings up well?

**Comment by alexcrichton** [comment]
Ah sorry I haven't looked into libgit2's ODB support yet, so I don't know how that would look here. For adding bindings you can define them in `libgit2-sys/lib.rs` and then run `cargo run` in the `systest` directory to verify them. Adding higher-level bindings is slightly more complicated, and depends on the APIs themselves

**Comment by drozdziak1** [comment]
Hey, just looked around the crate and there seems to be some `Odb` stuff in place, both bindings and idiomatic Rust code. Or maybe you meant something else?

**Comment by alexcrichton** [comment]
I think they're pretty empty right now, but if they're good enough for your use case that'd be great!

**Comment by drozdziak1** [comment]
Thanks for pointing me to Odb. It was just right for what I wanted to do. But, **is there a way currently to change a `Remote`'s url?** Because of how IPFS operates I need to change the remote URL every time someone's push alters my representation of the object tree. A limiting solution I thought about would probably be to roll with IPNS (PKI-guarded aliasing for IPFS links, pretty useful but overwriting a target of an alias is very time-consuming) only.

**Comment by drozdziak1** [comment]
Going with a `git-config` call for now.

**Comment by alexcrichton** [comment]
Perhaps! It'd be good to check libgit2 first and then if bindings are missing here we can add them here too

**Comment by drozdziak1** [comment]
Oh sorry, I didn't clarify. I *did* find the ref thing I needed eventually. Thanks!
