### ISSUE TITLE
CI build on Linux/OSX

### ISSUE THREAD

**Issue by rcjsuen** [alexcrichton/git2-rs#397]
I see that this project has a [`.travis.yml`](https://github.com/alexcrichton/git2-rs/blob/8448e672b00687341b72f8d9b34cac9e9586e245/.travis.yml) file but it doesn't seem to be integrated with GitHub. Was it turned off intentionally?

**Comment by alexcrichton** [comment]
Oh Travis just moved from org => com, so it's now at https://travis-ci.com/alexcrichton/git2-rs/
