### ISSUE TITLE
"authentication required but no callback set" on clone with SSH url

### ISSUE THREAD

**Issue by qrush** [alexcrichton/git2-rs#41]
Hey, maybe I'm doing something wrong here, but it doesn't seem like `Repository::clone` or `RepoBuilder` likes SSH urls, for example: `git@github.com:qrush/m.git`.

Maybe I'm missing something on linking/building? It seems like git2-rs includes libssl, etc.

**Comment by qrush** [comment]
PEBKAC

**Comment by alexcrichton** [comment]
I take it you ended up running across [`RemoteCallbacks`](http://alexcrichton.com/git2-rs/git2/struct.RemoteCallbacks.html)?

For posterity's sake that combined with [`RepoBuilder`](http://alexcrichton.com/git2-rs/git2/build/struct.RepoBuilder.html) should do the trick!

**Comment by qrush** [comment]
Yeah, I had to pass in a `credentials` callback, which i'm still trying to figure out. Stumbling around.

**Comment by alexcrichton** [comment]
You may want to take a look at [cargo's credential callback](https://github.com/rust-lang/cargo/blob/bb28e71202260180ecff658cd0fa0c7ba86d0296/src/cargo/sources/git/utils.rs#L344-L391) or [crates.io's credential callback](https://github.com/rust-lang/crates.io/blob/master/src/git.rs#L241-L250) for some inspiration.
