### ISSUE TITLE
Build fails when `PKG_CONFIG_PATH` env variable is not empty

### ISSUE THREAD

**Issue by gentoo90** [alexcrichton/git2-rs#63]
[build.rs:86](../blob/master/libgit2-sys/build.rs#L86) should add the bundled lib path to the *beginning*, not the end of `PKG_CONFIG_PATH`, or system-wide `libgit2` will be used if present, which can lead to build failures (like in Heather/gentoo-rust#124)

**Comment by alexcrichton** [comment]
Good point! Thanks for the report!
