### ISSUE TITLE
Will a rust binary using git2-rs work on a box without libgit2 installed?

### ISSUE THREAD

**Issue by bmcorser** [alexcrichton/git2-rs#70]
I'm making a little command line tool to smooth our release process, and want to distribute a binary using git2-rs to other developers in my company.

Will I have to get them to install libgit2 or will the relevant parts be included in the binary produced by cargo?

**Comment by alexcrichton** [comment]
It will indeed work without libgit2 installed! By default this library statically links libgit2, you'll have to opt into dynamic linking which is when it will require that libgit2 is installed locally.

**Comment by bmcorser** [comment]
:+1: I saw mentions of "static linking" in docs elsewhere, but wasn't sure if it applied in this case. Cool!
