### ISSUE TITLE
git2-rs panics when a checkout progress callack is given

### ISSUE THREAD

**Issue by tgkokk** [alexcrichton/git2-rs#78]
I tried to run the [`clone` example](https://github.com/alexcrichton/git2-rs/blob/master/examples/clone.rs) and it threw a `SIGILL` when it got to the checkout stage. I looked into it and I found that libgit calls `report_progress` (which calls the checkout callback) with `NULL` as the path [here](https://github.com/libgit2/libgit2/blob/47f37400253210f483d84fb9c2ecf44fb5986849/src/checkout.c#L2509), `report_progress` [here](https://github.com/libgit2/libgit2/blob/47f37400253210f483d84fb9c2ecf44fb5986849/src/checkout.c#L1613-L1621). Rust panics when it tries to read the string (and convert it to a byte array) [here](https://github.com/alexcrichton/git2-rs/blob/master/src/build.rs#L421).

The C# binding converts NULL to an empty string, the Ruby and Swift bindings passes `nil` to the callback, and neither Haskell or OCaml have bindings for any checkout functions (just to mention two languages that lack nil completely).

**Comment by alexcrichton** [comment]
Thanks for the report!
