### ISSUE TITLE
Shouldn't Diff constructors be just methods of Repository?

### ISSUE THREAD

**Issue by dpc** [alexcrichton/git2-rs#87]
I'm working on a project that is going to be wrapping libgit2 structs to get an API similiar to git2-rs, and Diff, having standalone constructors seems inconsistent with other parts of library (and is making my life more difficult, for reasons that are irrelevant here).

So it seems to me that `Diff::tree_to_tree` should be `Repository::diff_tree_to_tree`, just like eg. Index is constructed with `Repository::index()`

**Comment by alexcrichton** [comment]
Hm true, I think at the time I thought they were too involved to be present on `Repository`, but in retrospect I agree! I'll go ahead and do this.

**Comment by dpc** [comment]
Thanks!
