### ISSUE TITLE
Broken libgit2-sys 0.3 compatibility (bump to 0.4?)

### ISSUE THREAD

**Issue by lucab** [alexcrichton/git2-rs#89]
Commit 287be9ccb404668cf8f56643d83068ec8536031a, now part of libgit2-sys 0.3.8, broke compatibility with previous 0.3.7 API by moving around some pub constants.
You noticed yourself the effect of this when [touching cargo](https://github.com/rust-lang/cargo/commit/e0dff0f2dd6fceff892b8911aff32e3bec4e6a10#diff-0100d09db99ce0be7f3fa5d11c21864b).

According to vanilla semver, 0.3.7 and 0.3.8 are not forced to be compatible (rule 4, aka `v0 major`).
According to cargo semver, 0.3.7 and 0.3.8 are [considered compatible](http://doc.crates.io/crates-io.html#pre-10-versions).

It is my understanding that ligbit2-sys should be bumped to 0.4.

**Comment by alexcrichton** [comment]
Yeah this is true, although it's possible to be compatible with both by updating to using the constants from the intended locations. Along those lines I'd prefer to not bump this just yet (e.g. "minor changes" can be compatible with both) so I'm gonna leave it at 0.3 for now.

Thanks for the report though!
