### ISSUE TITLE
Fail to link if there is special chars in the project path

### ISSUE THREAD

**Issue by FerarDuanSednan** [alexcrichton/git2-rs#90]
If there is a special character in the path of the project ( like é,è ), libgit2-sys fail to link with the program. ex : /home/arnaud/workspace/D**é**pots/laughing-journey

It took me time to find why it suddenly stop building after adding git2 dependency.

To reproduce:
```bash
mkdir yès
cd yès
cargo new myproject
cd myproject
echo "git2 = \"0.3.3\" " >> Cargo.toml
cargo build
```
Here the output: [error.txt](https://github.com/alexcrichton/git2-rs/files/75580/error.txt)

**Comment by alexcrichton** [comment]
I seem to be able to reproduce the fact that an error happens, but not quite the exact error which is happening. Can you rerun with `RUST_BACKTRACE=1` and gist the result?

**Comment by FerarDuanSednan** [comment]
I hope this will help you:
```sh
cd yès
cargo new myproject
cd myproject
echo "git2 = \"0.3.3\" " >> Cargo.toml
RUST_BACKTRACE=1 cargo build
```
gist : https://gist.github.com/FerarDuanSednan/08bfc7cfe0c40a949bb5

**Comment by alexcrichton** [comment]
Ah right, so I tracked this down and found out this was b/c `pkg-config` printing some weird characters, so I believe that https://github.com/alexcrichton/git2-rs/commit/4d2b77171cf7001a4fc5821031e029ab10e4bba9 should fix this. Thanks for the report!
