### ISSUE TITLE
How to set cred callback for push?

### ISSUE THREAD

**Issue by ruscur** [alexcrichton/git2-rs#98]
I'm trying to push to a remote using SSH authentication.  Trying to do this "out of the box" yields the following:

```rust
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 23, message: "authentication required but no callback set" }', src/libcore/result.rs:741
```

which is fine, I haven't given it any authentication callback yet.

So, I tried to set the callback in what I think is the right place, by making a callbacks object:

```rust
let mut callbacks = RemoteCallbacks::new();
callbacks.credentials(|user, pass, ctype| {
    return Cred::ssh_key_from_agent(user);
});
```
However, the only method I could find on a Remote to set the callbacks was in update_tips, so I tried the following:

```rust
remote.update_tips(Some(&mut callbacks), false, AutotagOption::Auto, None).unwrap();
```
Which doesn't work because I haven't connected yet.  But if I try to:

```rust
remote.connect(Direction::Push).unwrap();
```
It fails since there's no creds.

I've gotta be missing something or doing something wrong, does anyone know what that is?

**Comment by alexcrichton** [comment]
You may want to try [`Remote::push`](http://alexcrichton.com/git2-rs/git2/struct.Remote.html#method.push) which has a [`PushOptions`](http://alexcrichton.com/git2-rs/git2/struct.PushOptions.html) argument which in turn should allow you to [specify the `RemoteCallbacks`](http://alexcrichton.com/git2-rs/git2/struct.PushOptions.html#method.remote_callbacks).

Does that work for you?

**Comment by ruscur** [comment]
Yeah, not sure how I missed that.  Cheers.
